### PR TITLE
Invalid path when section has no name.

### LINKED ISSUE #79: [development] Weekly format (possibly topics too) has wrong path if section has no name.
For example:

- http://moodle.test/course/Weekly/abc/24-week-1 (OK, abc is a section name)
- http://moodle.test/course/Weekly//25-week-2 (missing section name, it is shown as '7 June - 13 June').

### PR DESCRIPTION
**Pull request by roperto**
Fixes issue #79

### CODE REVIEW

File: classes/local/courseformat/simplesection_base.php [hunk 1]
```diff
@@ -51,14 +51,13 @@ private static function get_my_format() {
...
 
-    public static function find_section_by_slug($courseid, $sectionslug) {
-        global $DB;
-
-        $sections = $DB->get_records('course_sections', ['course' => $courseid]);
-        foreach ($sections as $section) {
-            $slug = clean_moodle_url::sluggify($section->name, false);
+    public static function find_section_by_slug($course, $sectionslug) {
+        $cminfo = get_fast_modinfo($course);
+        foreach (array_keys($cminfo->sections) as $sectionnum) {
```
Comment (dmitriim) [inline classes/local/courseformat/simplesection_base.php]: Could it be a case if module doesn't have any sections?

Comment (roperto) [inline classes/local/courseformat/simplesection_base.php]: It can be, and it will return null:

https://github.com/brendanheywood/moodle-local_cleanurls/blob/f9dae0f0e5887a5e669350c7768c82d397fe3aaa/classes/local/courseformat/simplesection_base.php#L64

If there is no section, it will try to see if there is an activity in the 'root' (invisible) section to use.
