### PR TITLE
WR #257591. Fixes #12. Found one place where expected and result were mixed up.

### LINKED ISSUE #12: Fix expected vs actual ordering of arguments in unit tests as needed
A few places the order of args is wrong

https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals

### PR DESCRIPTION
**Pull request by suankan**

### CODE REVIEW

File: tests/local_clean_urls.php [hunk 1]
```diff
@@ -181,16 +181,16 @@ public function test_local_cleanurls_simple() {
...
 
         // Nothing to unclean because these urls will get routed directly by apache not router.php.
 
         $url = 'http://www.example.com/moodle/user/profile.php?id=' . $this->staff->id;
         $murl = new moodle_url($url);
         $clean = $murl->out();
         $this->assertEquals($url, $clean, "Not Cleaned: user profile url with username");
-
         $url = 'http://www.example.com/moodle/user/view.php?id=' . $this->staff->id . '&course=' . $this->course->id;
+
```
Comment (brendanheywood) [inline tests/local_clean_urls.php]: Try to avoid random unrelated changes like this

Comment (brendanheywood) [inline tests/local_clean_urls.php]: Also try to make better commit messages:

> Found one place where expected and result were mixed up.

This makes almost no sense to someone looking back at this commit. Always try to say what changed from an absolute point of view, so something like

'Fixed swapped actual vs expected arguments in unit tests'

Comment (suankan) [inline tests/local_clean_urls.php]: I fixed the commit comment.

As for those lines, yeah, will keep that in mind. Just that time it was blurring my eyes because two blocks of code corresponding to two different test-cases were separated by line-break on wrong line.
